const str = require('fs')
  .readFileSync('./.list.dat', 'utf8')
  .split('\n')
  .filter(v =>
    v &&
    !v.startsWith('//') &&
    !v.startsWith('!') &&
    v.includes('.')
  )
  .map(v => v.replace('*.', ''))
  .sort((a, b) => a > b ? 1 : -1)
  .join(',')

console.log(`\
// THIS FILE WAS GENERATED BY './tools/tld/update.sh'
export default '${str}'`
)